### ISSUE TITLE
How do I make an existing user an admin

### ISSUE THREAD

**Issue by JimZipCode** [mastodon/documentation#1096]
I'm running Mastodon 4.0.2

1. Can this only be done from the command line? 

If so, WHY on earth?  Don't we want most routine user-management tasks done from the UI?

2. How to do it from command line?

This does not work:
```
root@mastodon:~# su - mastodon
mastodon@mastodon:~$ RAILS_ENV=production bundle exec rails mastodon:make_admin USERNAME=JimZipCode
Could not locate Gemfile or .bundle/ directory
mastodon@mastodon:~$ cd live
mastodon@mastodon:~/live$ RAILS_ENV=production bundle exec rails mastodon:make_admin USERNAME=MyUser
rails aborted!
Don't know how to build task 'mastodon:make_admin' (See the list of available tasks with `rails --tasks`)
Did you mean?  mastodon:stats
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task_manager.rb:59:in `[]'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:159:in `invoke_task'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/command.rb:50:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
(See full trace by running task with --trace)
```

I'll attach the out from the rails --tasks command.
[tasks_output.txt](https://github.com/mastodon/documentation/files/10144687/tasks_output.txt)

This also does not work:  

```
mastodon@mastodon:~/live$ RAILS_ENV=production bin/tootctl accounts modify MyUser --role admin
Cannot find user role with that name
```
That error message makes a sort of sense.  Admin is not a custom or user-defined role, it is a default role.  But then how do I put someone into it?

**Comment by trwnh** [comment]
4.0+ roles are case-sensitive

**Comment by JimZipCode** [comment]
Thanks. So what do I change my attempted-commands to?

**Comment by trwnh** [comment]
change `--role admin` to `--role Admin` i think
